### ISSUE TITLE
stddef.h: No such file or directory,

### ISSUE THREAD

**Issue by mrreznitsky** [JuniorDjjr/RealSkybox#1]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cstddef(12,10): fatal error C1083: stddef.h: No such file or directory,

**Comment by JuniorDjjr** [comment]
Check your `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\` directory. You may change it in project properties.
